(function() {
	"use strict";

	var sharedApi = {
		SUBMIT: {
			FORM: "SUBMIT_FORM",
			FORM_ERROR: "FORM_ERROR",
			SERVER_ERROR: "SERVER_ERROR",
			KRITIQUE_FORM: "KRITIQUE_FORM",
			TURNTO_QUESTION: "TURNTO_QUESTION",
			TURNTO_ANSWER: "TURNTO_ANSWER",
			STORE_LOCATOR: "SUBMIT_STORE_LOCATOR"
		},
		CHANGE: {
			FILTER_CHANGE: "FILTER_CHANGE"
		},
		CLICK: {
			ACCORDION_CLICK: "CLICK_ACCORDION",
			ADDTHIS_SHARE: "ADDTHIS_SHARE",
			ARTICLE_LINK: "CLICK_ARTICLE_LINK",
			BIN_CLICK: "BIN_CLICK",
			BREADCRUMBS_LINK: "CLICK_BREADCRUMBS_LINK",
			CAROUSEL_CLICK: "CLICK_CAROUSEL",
			CARTWIRE_RETAILER_CLICK: "CARTWIRE_RETAILER_CLICK",
			CLIC2BUY_BUTTON_CLICK: "CLIC2BUY_BUTTON_CLICK",
			CONSTANT_COMMERCE_BUTTON_CLICK: "CONSTANT_COMMERCE_BUTTON_CLICK",
			FORM_CLICK: "FORM_CLICK",
			IMAGE_CLICK: "CLICK_IMAGE",
			IMAGE_GALLERY_CLICK: "CLICK_IMAGE_GALLERY",
			KRITIQUE_HELPFUL: "KRITIQUE_HELPFUL",
			KRITIQUE_UNHELPFUL: "KRITIQUE_UNHELPFUL",
			KRITIQUE_READ_REVIEWS: "KRITIQUE_READ_REVIEWS",
			KRITIQUE_REPORT: "KRITIQUE_REPORT",
			KRITIQUE_WIDGET_CLOSE: "KRITIQUE_WIDGET_CLOSE",
			KRITIQUE_WRITE_REVIEW: "KRITIQUE_WRITE_REVIEW",
			LOAD_MORE_CLICK: "LOAD_MORE_CLICK",
			LINK_CLICK: "LINK_CLICK",
			LIVECHAT_BUTTON_CLICK: "LIVECHAT_BUTTON_CLICK",
			PRODUCT_QUICK_VIEW: "PRODUCT_QUICK_VIEW",
			PRODUCT_VARIANT_CLICK: "PRODUCT_VARIANT_CLICK",
			QUIZ_CTA: "QUIZ_CAT",
			QUIZ_RESULT: "QUIZ_RESULT",
			RECIPE_TO_BASKET: "RECIPE_TO_BASKET",
			SEARCH_FILTER: "SEARCH_FILTER",
			SITE_SEARCH: "SITE_SEARCH",
			SMARTLABEL_CLICK: "SMARTLABEL_CLICK",
			STORE_LOCATOR_EDIT: "STORE_LOCATOR_EDIT",
			STORE_LOCATOR_CTA: "STORE_LOCATOR_CTA",
			TABS_CLICK: "TABS_CLICK",
			TAGS_CLICK: "TAGS_CLICK",
			TURNTO_INACCURATE: "TURNTO_INACCURATE",
			TURNTO_SEE_QUESTION: "TURNTO_SEE_QUESTION",
			TURNTO_TEASER_SEE_QUESTION: "TURNTO_TEASER_SEE_QUESTION",
			VIRTUAL_AGENT_CLICK: "VIRTUAL_AGENT_CLICK"
		},
		LOAD: {
			FORM_PAGE: "FORM_PAGE",
			PRODUCT_INFO: "PRODUCT_INFO",
			VIRTUAL_AGENT: "VIRTUAL_AGENT",
			STORE_LOCATOR: "STORE_LOCATOR",
			PDP_PAGE_LOAD: "PDP_PAGE_LOAD"
		},
		OTHER: {
			BAZAARVOICE: "BAZAARVOICE",
			CLIC2BUY: "CLIC2BUY",
			KRITIQUE_RENDERER: "KRITIQUE_RENDERER",
			SHOPPABLE_INIT: "SHOPPABLE_INIT",
			SHOPPABLE_PURCHASE: "SHOPPABLE_PURCHASE",
			SHOPPABLE_CART_VIEW: "SHOPPABLE_CART_VIEW",
			STORE_LOCATOR_RESULTS: "STORE_LOCATOR_RESULTS",
			STORE_LOCATOR_OPTIONS: "STORE_LOCATOR_OPTIONS"
		},
		ctConstants: {
			Acquisition: "Acquisition: Mktg Opt ins",
			Acquisitionout: "Acquisition: Mktg Opt out",
			article: "article",
			articleView: "Article view",
			AttentionPing: "Attention Time",
			DiagnosticToolResults: "Dignostic Tool Results",
			ExternalLink: "External Link",
			RedeemCoupons: "Readeem Coupons",
			VideoFastForwarded: "Video Fast Forwarded",
			accordianClicked: "Accordian Clicked",
			addthisshare: "Add this Share",
			addtoCart: "addtoCart",
			addtobasket: "Add To Basket",
			advocacy: "Advocacy",
			anchorLinkClicked: "Anchor Link Clicked",
			applicationPlay: "Application Plays",
			articleClick: "Article Click",
			audioCompletes: "Audio Completes",
			audioPlays: "Audio Play",
			audioProgress: "Audio Progress",
			bazaaarvoicerenders: "Bazaar Voice Renders",
			bazaarvoiceratingreview: "Bazaar Voice rating Review Submitted",
			bazaarvoicereformcloses: "Bazaar Voice Review Close",
			bazaarvoicereviewopen: "Bazaar Voice Review Open",
			buttonclicked: "Button Clicked",
			bvclose: "Bazaar Voice Rating/Review Close",
			bvopen: "Bazaar Voice Rating/Review Open",
			bvrenders: "BazaarVoice Renders",
			callToAction: "Call to Action",
			cartView: "Cart View",
			campaign: "Campaign",
			campstep: "Campaign Step",
			carouselClick: "Carousel Click",
			changecontentfocus: "Change Content Focus",
			chat: "Chat",
			chatopen: "Chat Open",
			chatBotOpen: "ChatBot Open",
			checkoutenhanced: "checkoutenhanced",
			cta: "cta",
			clic2buy: "Clic2Buy",
			clickToRecipe: "Click To Recipe",
			clickstosocialplatforms: "Clicks to Social Platforms",
			clicktoaction: "Click To Action",
			clicktopurchasebundle: " Click To Purchase Bundle",
			closecontentfocus: "Close Content Focus",
			comments: "Comments",
			constantCommerce: "Constant Commerce",
			contactus: "Contact-Us",
			contactUsStart: "Contact Us Form Start",
			contactUsSubmit: "Contact Us Form Submit",
			contestEntries: "Contest Entries",
			continueShopping: "Continue Shopping",
			conversion: "Conversion",
			countryselected: "Country Selected",
			coupon: "Coupons",
			couponSelected: "Coupon Selected",
			custom: "Custom",
			deleteproduct: "Delete Product",
			diagtoolcta: "Diag Tool CTA",
			diagtoolemail: "Diag Tool Email",
			diagtooleve: "Diag Tool Event",
			diversion: "Diversion",
			donation: "Donations",
			downloads: "Downloads",
			dropDown: "Drop Down",
			dynamicerror: "Dynamic Error",
			editorPick: "Editors Pick",
			email: "Email",
			engagement: "Engagement",
			errorPage: "Error Page",
			featuredcategory: "Featured Category",
			featuredsocialtopic: "Featured-social-topic",
			featuredtweetTab: "Featured Tweet Tab",
			filter: "Filter",
			followOntwitter: "Follow on Twitter",
			followaccount: "Follow Account",
			forms: "Forms",
			ftap: "FTAF",
			gameDownloads: "Game Downloads",
			gamePlay: "Game Plays",
			gamecomplete: "Game Completes",
			gamelevelsplayed: "Game Levels Played",
			iFrame: "iFrame",
			imageclick: "Image Click",
			imageload: "Image Upload",
			inputerror: "Input Error",
			instantwins: "Instant Wins",
			intendToSignup: "Intend To Sign Up",
			interest: "Interest",
			languageSelector: "Language Selector",
			lead: "Lead",
			leftrightquickview: "Left right Quickview",
			like: "Like",
			listing: "Listing",
			linkClick: "Link Click",
			loadMore: "Load More",
			mayLike: "You May Also Like",
			miniBag: "Mini Bag",
			multiplerelatedtweets: "Multiple Related Tweets",
			mute: "Mute",
			navigation: "Navigation",
			newsletter: "newsletter",
			ordersummary: "Order Summary",
			other: "Other",
			outboundLinkClicked: "Outbound Link Clicked",
			pageScroll: "Page Scroll",
			pagedwelltiming: "Page Dwell Timing",
			pagination: "Pagination",
			personalizegift: "Personalize Gift",
			pinterst: "Pinterest",
			print: "Print",
			product: "product",
			productImpression: "Product Impression",
			productInfo: "Product Info",
			productQuickView: "Product Quick View",
			productawards: "Product Awards",
			productclick: "productClick",
			profileEdit: "Profile Edit",
			promotionClick: "promotionClick",
			promotionView: "promotionView",
			purchase: "Click to Purchase",
			purchaseIntent: "Purchase Intent",
			purchaseIntendcoupon: "Purchase Intend: Coupon Requests",
			purchaseIntendsample: "Purchase Intend: Sample Requests",
			purchaseOrder: "Purchase: Order",
			purchaseenhanced: "Purchase",
			quickPoll: "Quick Poll",
			rangePDP: "Product Range-PDP",
			ratingreview: "Rating/Review",
			read: "Read",
			readMore: "Read More",
			readReviews: "Read reviews",
			recipeClick: "Recipe Click",
			recipeListing: "Recipe Listing",
			recommend: "Recommend",
			referral: "Referral",
			registration: "Registration",
			relatedArticle: "Related Article",
			removecart: "Cart Remove",
			retailerClick: "Retailer Click",
			reviewHelpful: "Review Helpful",
			reviewIntent: "Review Intent",
			reviewIntentBazaarVoice: "Bazaar Voice Review Intent",
			rrClose: "Rating Review Close",
			rrHelpful: "Rating Review Helpful",
			rrNotHelpful: "Rating Review Not Helpful",
			rrOpen: "Rating Review Open",
			rrRenders: "Rating Review Renders",
			rrReported: "Rating Review Reported",
			share: "Share",
			shopNow: "ShopNow",
			signIns: "Sign Ins",
			signup: "signup",
			signupStart: "SignUp Start",
			signupSubmit: "SignUp Submit",
			signOut: "Sign Out",
			searchResults: "Search Results",
			serverError: "Server-Side Error",
			siteSearch: "Site Search",
			smartlabelClick: "Smart Label Click",
			smartlabelExit: "Smart Label Exit",
			socialcommunity: "Social Community",
			socialcomponentcta: "Social Component CTA",
			sortReviews: "Sort Reviews",
			spincarousel: "Spin Carousel",
			storeLocator: "Store Locator",
			storesearch: "Store Search",
			storesearchedit: "Store Search Edit",
			submission: "Submission",
			survey: "Survey",
			subscribeNewsletter: "Subscriptions - Newsletter Sign up",
			suscribeUpdate: "Subscribe for Updates",
			tabClick: "Tab Click",
			tags: "Tags",
			trackEvent: "trackEvent",
			trackEventnewslettersignup: "trackEventnewslettersignup",
			turnto: "Turn To",
			tweet: "Tweet",
			unmute: "Unmute",
			uploads: "Uploads",
			videoAutoPlays: "Video Auto Play",
			videoCompletes: "Video Completes",
			videoPlays: "Video Plays",
			videoProgress: "Video Progress",
			viewBag: "View Bag",
			viewPrize: "View Prize",
			viewonyoutube: "View on Youtube",
			virtualagent: "Virtual Agent",
			widgets: "Widgets",
			win: "Win",
			youtube: "YouTube",
			shopalystRetailerClicked: "RETAILER_CLICKED"
		}

	};

	Cog.registerStatic({
		name: "analytics.eventsDefinition",
		sharedApi: sharedApi,
		api: {}
	});
})();
